build: cure partial specialization after instantiation
this block needs to be moved to v8.h.

ninja: Entering directory `out/Release'
[1/8047] CXX obj/third_party/blink/renderer/modules/media_controls/media_controls/media_control_button_panel_element.o
FAILED: obj/third_party/blink/renderer/modules/media_controls/media_controls/media_control_button_panel_element.o
g++ -MMD -MF obj/third_party/blink/renderer/modules/media_controls/media_controls/media_control_button_panel_element.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_MODULES_IMPLEMENTATION=1 -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DWEBP_EXTERN=extern -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DVK_NO_PROTOTYPES -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DNO_MAIN_THREAD_WRAPPING -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_GL -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_HAS_JPEG_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DVK_NO_PROTOTYPES -DV8_DEPRECATION_WARNINGS -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_PLATFORM_CHROMIUM=1 -DSUPPORT_WEBGL2_COMPUTE_CONTEXT=1 -DWTF_USE_WEBAUDIO_PFFFT=1 -DUSE_LIBJPEG_TURBO=1 -DV8_DEPRECATION_WARNINGS -DLIBXSLT_STATIC -I../.. -Igen -I../../third_party/libyuv/include -I../../third_party/libwebp/src -I../../third_party/khronos -I../../gpu -I../../third_party/vulkan/include -Igen/third_party/dawn -I../../third_party/dawn/src/include -I../../third_party/boringssl/src/include -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/abseil-cpp -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/protobuf/src -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/skia -I../../third_party/vulkan/include -I../../third_party/skia/third_party/vulkanmemoryallocator -I../../third_party/vulkan/include -I../../third_party/angle/include -I../../third_party/angle/src/common/third_party/base -Igen/angle -I../../third_party/angle/include -I../../v8/include -Igen/v8/include -I../../third_party/libwebm/source -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libjpeg_turbo -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/ots/include -I../../v8/include -Igen/v8/include -I../../third_party/libxml/src/include -I../../third_party/libxml/linux/include -I../../third_party/libxslt/src -I../../third_party/snappy/src -I../../third_party/snappy/linux -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -fvisibility=hidden -g0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/nss3 -I/usr/include/nspr4 -DLIBXML_STATIC= -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../third_party/blink/renderer/modules/media_controls/elements/media_control_button_panel_element.cc -o obj/third_party/blink/renderer/modules/media_controls/media_controls/media_control_button_panel_element.o
In file included from ../../third_party/blink/renderer/core/css/css_primitive_value.h:28,
                 from ../../third_party/blink/renderer/core/dom/element.h:32,
                 from ../../third_party/blink/renderer/core/html/html_element.h:27,
                 from ../../third_party/blink/renderer/core/html/html_div_element.h:27,
                 from ../../third_party/blink/renderer/modules/media_controls/elements/media_control_div_element.h:8,
                 from ../../third_party/blink/renderer/modules/media_controls/elements/media_control_button_panel_element.h:8,
                 from ../../third_party/blink/renderer/modules/media_controls/elements/media_control_button_panel_element.cc:5:
../../third_party/blink/renderer/platform/wtf/casting.h: In static member function ‘static bool blink::DowncastTraits<T>::AllowFrom(const U&)’:
../../third_party/blink/renderer/platform/wtf/casting.h:60:3: warning: no return statement in function returning non-void [-Wreturn-type]
   60 |   }
      |   ^
In file included from ../../third_party/blink/renderer/platform/bindings/script_wrappable.h:37,
                 from ../../third_party/blink/renderer/core/dom/events/event_target.h:45,
                 from ../../third_party/blink/renderer/core/dom/node.h:32,
                 from ../../third_party/blink/renderer/core/dom/container_node.h:31,
                 from ../../third_party/blink/renderer/core/dom/element.h:35,
                 from ../../third_party/blink/renderer/core/html/html_element.h:27,
                 from ../../third_party/blink/renderer/core/html/html_div_element.h:27,
                 from ../../third_party/blink/renderer/modules/media_controls/elements/media_control_div_element.h:8,
                 from ../../third_party/blink/renderer/modules/media_controls/elements/media_control_button_panel_element.h:8,
                 from ../../third_party/blink/renderer/modules/media_controls/elements/media_control_button_panel_element.cc:5:
../../third_party/blink/renderer/platform/bindings/trace_wrapper_v8_reference.h: At global scope:
../../third_party/blink/renderer/platform/bindings/trace_wrapper_v8_reference.h:17:8: error: partial specialization of ‘struct v8::TracedGlobalTrait<v8::TracedGlobal<T> >’ after instantiation of ‘struct v8::TracedGlobalTrait<v8::TracedGlobal<v8::Object> >’ [-fpermissive]
   17 | struct TracedGlobalTrait<v8::TracedGlobal<T>> {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.